name: Android Release Build

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch: # Allows manual trigger from GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: wrapper

      - name: Build and Sign Release AAB
        id: sign_app
        run: |
          gradle bundleRelease -Pandroid.injected.signing.store.file=${{ github.workspace }}/app/keystore.jks -Pandroid.injected.signing.store.password='an0605FE#$' -Pandroid.injected.signing.key.alias=key0 -Pandroid.injected.signing.key.password='an0605FE#$'
          echo "signedReleaseFile=app/build/outputs/bundle/release/app-release.aab" >> $GITHUB_OUTPUT

      - name: Upload Signed AAB
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: ${{steps.sign_app.outputs.signedReleaseFile}}
          
      - name: Deploy to Google Play (Internal Testing)
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: com.cosmetictracker
          releaseFiles: ${{steps.sign_app.outputs.signedReleaseFile}}
          track: internal
